# Generated by Django 4.2.30 on 2026-05-26 18:31

import boards.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0005_boardchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='attachments',
            field=models.JSONField(blank=True, default=boards.models.default_json_list),
        ),
        migrations.AddField(
            model_name='card',
            name='checklist',
            field=models.JSONField(blank=True, default=boards.models.default_json_list),
        ),
        migrations.AddField(
            model_name='card',
            name='labels',
            field=models.JSONField(blank=True, default=boards.models.default_json_list),
        ),
        migrations.AddField(
            model_name='card',
            name='priority',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='story_points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
