# Generated by Django 4.2.30 on 2026-05-26 19:29

from django.db import migrations


def seed_owner_memberships(apps, schema_editor):
    Board = apps.get_model("boards", "Board")
    BoardMembership = apps.get_model("boards", "BoardMembership")

    for board in Board.objects.all():
        BoardMembership.objects.get_or_create(
            board=board,
            user=board.owner,
            defaults={"role": "owner"},
        )


def reverse_seed(apps, schema_editor):
    BoardMembership = apps.get_model("boards", "BoardMembership")
    BoardMembership.objects.filter(role="owner").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_boardmembership'),
    ]

    operations = [
        migrations.RunPython(seed_owner_memberships, reverse_seed),
    ]
