# Generated by Django 4.2.30 on 2026-05-25 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamRoleLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('rank', models.PositiveIntegerField(help_text='Lower rank = higher authority (0 is top of hierarchy).')),
                ('can_manage_team', models.BooleanField(default=False)),
                ('can_manage_members', models.BooleanField(default=False)),
                ('can_manage_boards', models.BooleanField(default=False)),
                ('can_edit_boards', models.BooleanField(default=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_role_level', to='auth.group')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_levels', to='teams.team')),
            ],
            options={
                'ordering': ['rank', 'id'],
                'unique_together': {('team', 'rank'), ('team', 'slug'), ('team', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('role_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='teams.teamrolelevel')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role_level__rank', 'user__username'],
                'unique_together': {('user', 'team')},
            },
        ),
    ]
